# Generated by Django 3.2.7 on 2021-10-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDBapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='graph',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
